// Mock data for the design prototype. Generated from a game's analyse_game()
// output + Stockfish. Backend note: `san`, `best`, `best_san`, `is_capture`,
// `accuracy`, `counts`, `start_eval` are extra fields the UI needs.
const GAME = {
  "game_id": "abc123",
  "source": "chess.com",
  "start_eval": 47,
  "link": "https://www.chess.com/game/171307918776",
  "date": "2026-07-09",
  "time_control": "180",
  "result": "1-0",
  "termination": "kenan_nuraliyev won by checkmate",
  "eco": "C00",
  "opening": "French Defense: Knight Variation",
  "white": {
    "name": "kenan_nuraliyev",
    "elo": 304
  },
  "black": {
    "name": "MarmarmarUwU",
    "elo": 303
  },
  "accuracy": {
    "white": 84.6,
    "black": 78.8
  },
  "counts": {
    "white": {
      "Best": 15,
      "Excellent": 6,
      "Good": 3,
      "Book": 2,
      "Forced": 0,
      "Inaccuracy": 4,
      "Mistake": 1,
      "Miss": 1,
      "Blunder": 3
    },
    "black": {
      "Best": 8,
      "Excellent": 7,
      "Good": 3,
      "Book": 2,
      "Forced": 1,
      "Inaccuracy": 6,
      "Mistake": 3,
      "Miss": 2,
      "Blunder": 2
    }
  },
  "moves": [
    {
      "move_number": 1,
      "move": "e2e4",
      "mover": "white",
      "to_move": "black",
      "mate_in": null,
      "evaluation": 37,
      "category": "Book",
      "fen": "rnbqkbnr/pppppppp/8/8/4P3/8/PPPP1PPP/RNBQKBNR b KQkq - 0 1",
      "san": "e4",
      "best": "e2e4",
      "best_san": "e4",
      "is_capture": false
    },
    {
      "move_number": 1,
      "move": "e7e6",
      "mover": "black",
      "to_move": "white",
      "mate_in": null,
      "evaluation": 47,
      "category": "Book",
      "fen": "rnbqkbnr/pppp1ppp/4p3/8/4P3/8/PPPP1PPP/RNBQKBNR w KQkq - 0 2",
      "san": "e6",
      "best": "c7c5",
      "best_san": "c5",
      "is_capture": false
    },
    {
      "move_number": 2,
      "move": "g1f3",
      "mover": "white",
      "to_move": "black",
      "mate_in": null,
      "evaluation": 35,
      "category": "Book",
      "fen": "rnbqkbnr/pppp1ppp/4p3/8/4P3/5N2/PPPP1PPP/RNBQKB1R b KQkq - 1 2",
      "san": "Nf3",
      "best": "d2d4",
      "best_san": "d4",
      "is_capture": false
    },
    {
      "move_number": 2,
      "move": "d7d5",
      "mover": "black",
      "to_move": "white",
      "mate_in": null,
      "evaluation": 33,
      "category": "Book",
      "fen": "rnbqkbnr/ppp2ppp/4p3/3p4/4P3/5N2/PPPP1PPP/RNBQKB1R w KQkq - 0 3",
      "san": "d5",
      "best": "d7d5",
      "best_san": "d5",
      "is_capture": false
    },
    {
      "move_number": 3,
      "move": "e4d5",
      "mover": "white",
      "to_move": "black",
      "mate_in": null,
      "evaluation": 25,
      "category": "Excellent",
      "fen": "rnbqkbnr/ppp2ppp/4p3/3P4/8/5N2/PPPP1PPP/RNBQKB1R b KQkq - 0 3",
      "san": "exd5",
      "best": "e4e5",
      "best_san": "e5",
      "is_capture": true
    },
    {
      "move_number": 3,
      "move": "e6d5",
      "mover": "black",
      "to_move": "white",
      "mate_in": null,
      "evaluation": 33,
      "category": "Best",
      "fen": "rnbqkbnr/ppp2ppp/8/3p4/8/5N2/PPPP1PPP/RNBQKB1R w KQkq - 0 4",
      "san": "exd5",
      "best": "e6d5",
      "best_san": "exd5",
      "is_capture": true
    },
    {
      "move_number": 4,
      "move": "f3e5",
      "mover": "white",
      "to_move": "black",
      "mate_in": null,
      "evaluation": -50,
      "category": "Inaccuracy",
      "fen": "rnbqkbnr/ppp2ppp/8/3pN3/8/8/PPPP1PPP/RNBQKB1R b KQkq - 1 4",
      "san": "Ne5",
      "best": "d2d4",
      "best_san": "d4",
      "is_capture": false
    },
    {
      "move_number": 4,
      "move": "d8e7",
      "mover": "black",
      "to_move": "white",
      "mate_in": null,
      "evaluation": -43,
      "category": "Excellent",
      "fen": "rnb1kbnr/ppp1qppp/8/3pN3/8/8/PPPP1PPP/RNBQKB1R w KQkq - 2 5",
      "san": "Qe7",
      "best": "d8e7",
      "best_san": "Qe7",
      "is_capture": false
    },
    {
      "move_number": 5,
      "move": "d1e2",
      "mover": "white",
      "to_move": "black",
      "mate_in": null,
      "evaluation": -40,
      "category": "Best",
      "fen": "rnb1kbnr/ppp1qppp/8/3pN3/8/8/PPPPQPPP/RNB1KB1R b KQkq - 3 5",
      "san": "Qe2",
      "best": "d1e2",
      "best_san": "Qe2",
      "is_capture": false
    },
    {
      "move_number": 5,
      "move": "f7f6",
      "mover": "black",
      "to_move": "white",
      "mate_in": null,
      "evaluation": -43,
      "category": "Excellent",
      "fen": "rnb1kbnr/ppp1q1pp/5p2/3pN3/8/8/PPPPQPPP/RNB1KB1R w KQkq - 0 6",
      "san": "f6",
      "best": "f7f6",
      "best_san": "f6",
      "is_capture": false
    },
    {
      "move_number": 6,
      "move": "e5c4",
      "mover": "white",
      "to_move": "black",
      "mate_in": null,
      "evaluation": -437,
      "category": "Blunder",
      "fen": "rnb1kbnr/ppp1q1pp/5p2/3p4/2N5/8/PPPPQPPP/RNB1KB1R b KQkq - 1 6",
      "san": "Nc4",
      "best": "e5f3",
      "best_san": "Nf3",
      "is_capture": false
    },
    {
      "move_number": 6,
      "move": "e7e2",
      "mover": "black",
      "to_move": "white",
      "mate_in": null,
      "evaluation": -424,
      "category": "Excellent",
      "fen": "rnb1kbnr/ppp3pp/5p2/3p4/2N5/8/PPPPqPPP/RNB1KB1R w KQkq - 0 7",
      "san": "Qxe2+",
      "best": "d5c4",
      "best_san": "dxc4",
      "is_capture": true
    },
    {
      "move_number": 7,
      "move": "f1e2",
      "mover": "white",
      "to_move": "black",
      "mate_in": null,
      "evaluation": -417,
      "category": "Best",
      "fen": "rnb1kbnr/ppp3pp/5p2/3p4/2N5/8/PPPPBPPP/RNB1K2R b KQkq - 0 7",
      "san": "Bxe2",
      "best": "f1e2",
      "best_san": "Bxe2",
      "is_capture": true
    },
    {
      "move_number": 7,
      "move": "c8e6",
      "mover": "black",
      "to_move": "white",
      "mate_in": null,
      "evaluation": -25,
      "category": "Miss",
      "fen": "rn2kbnr/ppp3pp/4bp2/3p4/2N5/8/PPPPBPPP/RNB1K2R w KQkq - 1 8",
      "san": "Be6",
      "best": "d5c4",
      "best_san": "dxc4",
      "is_capture": false
    },
    {
      "move_number": 8,
      "move": "c4a5",
      "mover": "white",
      "to_move": "black",
      "mate_in": null,
      "evaluation": -25,
      "category": "Best",
      "fen": "rn2kbnr/ppp3pp/4bp2/N2p4/8/8/PPPPBPPP/RNB1K2R b KQkq - 2 8",
      "san": "Na5",
      "best": "c4a5",
      "best_san": "Na5",
      "is_capture": false
    },
    {
      "move_number": 8,
      "move": "f8d6",
      "mover": "black",
      "to_move": "white",
      "mate_in": null,
      "evaluation": 154,
      "category": "Mistake",
      "fen": "rn2k1nr/ppp3pp/3bbp2/N2p4/8/8/PPPPBPPP/RNB1K2R w KQkq - 3 9",
      "san": "Bd6",
      "best": "b7b6",
      "best_san": "b6",
      "is_capture": false
    },
    {
      "move_number": 9,
      "move": "d2d4",
      "mover": "white",
      "to_move": "black",
      "mate_in": null,
      "evaluation": -43,
      "category": "Miss",
      "fen": "rn2k1nr/ppp3pp/3bbp2/N2p4/3P4/8/PPP1BPPP/RNB1K2R b KQkq - 0 9",
      "san": "d4",
      "best": "a5b7",
      "best_san": "Nxb7",
      "is_capture": false
    },
    {
      "move_number": 9,
      "move": "b8c6",
      "mover": "black",
      "to_move": "white",
      "mate_in": null,
      "evaluation": 79,
      "category": "Mistake",
      "fen": "r3k1nr/ppp3pp/2nbbp2/N2p4/3P4/8/PPP1BPPP/RNB1K2R w KQkq - 1 10",
      "san": "Nc6",
      "best": "b7b6",
      "best_san": "b6",
      "is_capture": false
    },
    {
      "move_number": 10,
      "move": "a5c6",
      "mover": "white",
      "to_move": "black",
      "mate_in": null,
      "evaluation": -3,
      "category": "Inaccuracy",
      "fen": "r3k1nr/ppp3pp/2Nbbp2/3p4/3P4/8/PPP1BPPP/RNB1K2R b KQkq - 0 10",
      "san": "Nxc6",
      "best": "a5b7",
      "best_san": "Nxb7",
      "is_capture": true
    },
    {
      "move_number": 10,
      "move": "b7c6",
      "mover": "black",
      "to_move": "white",
      "mate_in": null,
      "evaluation": 2,
      "category": "Best",
      "fen": "r3k1nr/p1p3pp/2pbbp2/3p4/3P4/8/PPP1BPPP/RNB1K2R w KQkq - 0 11",
      "san": "bxc6",
      "best": "b7c6",
      "best_san": "bxc6",
      "is_capture": true
    },
    {
      "move_number": 11,
      "move": "b1c3",
      "mover": "white",
      "to_move": "black",
      "mate_in": null,
      "evaluation": -34,
      "category": "Good",
      "fen": "r3k1nr/p1p3pp/2pbbp2/3p4/3P4/2N5/PPP1BPPP/R1B1K2R b KQkq - 1 11",
      "san": "Nc3",
      "best": "b2b3",
      "best_san": "b3",
      "is_capture": false
    },
    {
      "move_number": 11,
      "move": "g8e7",
      "mover": "black",
      "to_move": "white",
      "mate_in": null,
      "evaluation": -19,
      "category": "Excellent",
      "fen": "r3k2r/p1p1n1pp/2pbbp2/3p4/3P4/2N5/PPP1BPPP/R1B1K2R w KQkq - 2 12",
      "san": "Ne7",
      "best": "e6f5",
      "best_san": "Bf5",
      "is_capture": false
    },
    {
      "move_number": 12,
      "move": "a2a4",
      "mover": "white",
      "to_move": "black",
      "mate_in": null,
      "evaluation": -105,
      "category": "Inaccuracy",
      "fen": "r3k2r/p1p1n1pp/2pbbp2/3p4/P2P4/2N5/1PP1BPPP/R1B1K2R b KQkq - 0 12",
      "san": "a4",
      "best": "c3a4",
      "best_san": "Na4",
      "is_capture": false
    },
    {
      "move_number": 12,
      "move": "c6c5",
      "mover": "black",
      "to_move": "white",
      "mate_in": null,
      "evaluation": 27,
      "category": "Mistake",
      "fen": "r3k2r/p1p1n1pp/3bbp2/2pp4/P2P4/2N5/1PP1BPPP/R1B1K2R w KQkq - 0 13",
      "san": "c5",
      "best": "e7f5",
      "best_san": "Nf5",
      "is_capture": false
    },
    {
      "move_number": 13,
      "move": "d4c5",
      "mover": "white",
      "to_move": "black",
      "mate_in": null,
      "evaluation": 12,
      "category": "Excellent",
      "fen": "r3k2r/p1p1n1pp/3bbp2/2Pp4/P7/2N5/1PP1BPPP/R1B1K2R b KQkq - 0 13",
      "san": "dxc5",
      "best": "c3b5",
      "best_san": "Nb5",
      "is_capture": true
    },
    {
      "move_number": 13,
      "move": "d6c5",
      "mover": "black",
      "to_move": "white",
      "mate_in": null,
      "evaluation": 11,
      "category": "Best",
      "fen": "r3k2r/p1p1n1pp/4bp2/2bp4/P7/2N5/1PP1BPPP/R1B1K2R w KQkq - 0 14",
      "san": "Bxc5",
      "best": "d6c5",
      "best_san": "Bxc5",
      "is_capture": true
    },
    {
      "move_number": 14,
      "move": "c3b5",
      "mover": "white",
      "to_move": "black",
      "mate_in": null,
      "evaluation": -8,
      "category": "Excellent",
      "fen": "r3k2r/p1p1n1pp/4bp2/1Nbp4/P7/8/1PP1BPPP/R1B1K2R b KQkq - 1 14",
      "san": "Nb5",
      "best": "e1g1",
      "best_san": "O-O",
      "is_capture": false
    },
    {
      "move_number": 14,
      "move": "a8c8",
      "mover": "black",
      "to_move": "white",
      "mate_in": null,
      "evaluation": 41,
      "category": "Good",
      "fen": "2r1k2r/p1p1n1pp/4bp2/1Nbp4/P7/8/1PP1BPPP/R1B1K2R w KQk - 2 15",
      "san": "Rc8",
      "best": "e8d7",
      "best_san": "Kd7",
      "is_capture": false
    },
    {
      "move_number": 15,
      "move": "f2f3",
      "mover": "white",
      "to_move": "black",
      "mate_in": null,
      "evaluation": -99,
      "category": "Mistake",
      "fen": "2r1k2r/p1p1n1pp/4bp2/1Nbp4/P7/5P2/1PP1B1PP/R1B1K2R b KQk - 0 15",
      "san": "f3",
      "best": "c1e3",
      "best_san": "Be3",
      "is_capture": false
    },
    {
      "move_number": 15,
      "move": "c7c6",
      "mover": "black",
      "to_move": "white",
      "mate_in": null,
      "evaluation": -96,
      "category": "Best",
      "fen": "2r1k2r/p3n1pp/2p1bp2/1Nbp4/P7/5P2/1PP1B1PP/R1B1K2R w KQk - 0 16",
      "san": "c6",
      "best": "c7c6",
      "best_san": "c6",
      "is_capture": false
    },
    {
      "move_number": 16,
      "move": "b5a7",
      "mover": "white",
      "to_move": "black",
      "mate_in": null,
      "evaluation": -352,
      "category": "Blunder",
      "fen": "2r1k2r/N3n1pp/2p1bp2/2bp4/P7/5P2/1PP1B1PP/R1B1K2R b KQk - 0 16",
      "san": "Nxa7",
      "best": "b5a3",
      "best_san": "Na3",
      "is_capture": true
    },
    {
      "move_number": 16,
      "move": "c8c7",
      "mover": "black",
      "to_move": "white",
      "mate_in": null,
      "evaluation": -252,
      "category": "Inaccuracy",
      "fen": "4k2r/N1r1n1pp/2p1bp2/2bp4/P7/5P2/1PP1B1PP/R1B1K2R w KQk - 1 17",
      "san": "Rc7",
      "best": "c5a7",
      "best_san": "Bxa7",
      "is_capture": false
    },
    {
      "move_number": 17,
      "move": "a7c6",
      "mover": "white",
      "to_move": "black",
      "mate_in": null,
      "evaluation": -261,
      "category": "Best",
      "fen": "4k2r/2r1n1pp/2N1bp2/2bp4/P7/5P2/1PP1B1PP/R1B1K2R b KQk - 0 17",
      "san": "Nxc6",
      "best": "a7c6",
      "best_san": "Nxc6",
      "is_capture": true
    },
    {
      "move_number": 17,
      "move": "c7c6",
      "mover": "black",
      "to_move": "white",
      "mate_in": null,
      "evaluation": -168,
      "category": "Inaccuracy",
      "fen": "4k2r/4n1pp/2r1bp2/2bp4/P7/5P2/1PP1B1PP/R1B1K2R w KQk - 0 18",
      "san": "Rxc6",
      "best": "e7c6",
      "best_san": "Nxc6",
      "is_capture": true
    },
    {
      "move_number": 18,
      "move": "e2b5",
      "mover": "white",
      "to_move": "black",
      "mate_in": null,
      "evaluation": -173,
      "category": "Best",
      "fen": "4k2r/4n1pp/2r1bp2/1Bbp4/P7/5P2/1PP3PP/R1B1K2R b KQk - 1 18",
      "san": "Bb5",
      "best": "e2b5",
      "best_san": "Bb5",
      "is_capture": false
    },
    {
      "move_number": 18,
      "move": "e6d7",
      "mover": "black",
      "to_move": "white",
      "mate_in": null,
      "evaluation": -78,
      "category": "Inaccuracy",
      "fen": "4k2r/3bn1pp/2r2p2/1Bbp4/P7/5P2/1PP3PP/R1B1K2R w KQk - 2 19",
      "san": "Bd7",
      "best": "e8f7",
      "best_san": "Kf7",
      "is_capture": false
    },
    {
      "move_number": 19,
      "move": "b5c6",
      "mover": "white",
      "to_move": "black",
      "mate_in": null,
      "evaluation": -97,
      "category": "Best",
      "fen": "4k2r/3bn1pp/2B2p2/2bp4/P7/5P2/1PP3PP/R1B1K2R b KQk - 0 19",
      "san": "Bxc6",
      "best": "b5c6",
      "best_san": "Bxc6",
      "is_capture": true
    },
    {
      "move_number": 19,
      "move": "d7c6",
      "mover": "black",
      "to_move": "white",
      "mate_in": null,
      "evaluation": -27,
      "category": "Inaccuracy",
      "fen": "4k2r/4n1pp/2b2p2/2bp4/P7/5P2/1PP3PP/R1B1K2R w KQk - 0 20",
      "san": "Bxc6",
      "best": "e7c6",
      "best_san": "Nxc6",
      "is_capture": true
    },
    {
      "move_number": 20,
      "move": "a4a5",
      "mover": "white",
      "to_move": "black",
      "mate_in": null,
      "evaluation": -124,
      "category": "Inaccuracy",
      "fen": "4k2r/4n1pp/2b2p2/P1bp4/8/5P2/1PP3PP/R1B1K2R b KQk - 0 20",
      "san": "a5",
      "best": "c1d2",
      "best_san": "Bd2",
      "is_capture": false
    },
    {
      "move_number": 20,
      "move": "c5b4",
      "mover": "black",
      "to_move": "white",
      "mate_in": null,
      "evaluation": -22,
      "category": "Inaccuracy",
      "fen": "4k2r/4n1pp/2b2p2/P2p4/1b6/5P2/1PP3PP/R1B1K2R w KQk - 1 21",
      "san": "Bb4+",
      "best": "e7f5",
      "best_san": "Nf5",
      "is_capture": false
    },
    {
      "move_number": 21,
      "move": "c2c3",
      "mover": "white",
      "to_move": "black",
      "mate_in": null,
      "evaluation": -22,
      "category": "Best",
      "fen": "4k2r/4n1pp/2b2p2/P2p4/1b6/2P2P2/1P4PP/R1B1K2R b KQk - 0 21",
      "san": "c3",
      "best": "c2c3",
      "best_san": "c3",
      "is_capture": false
    },
    {
      "move_number": 21,
      "move": "b4a5",
      "mover": "black",
      "to_move": "white",
      "mate_in": null,
      "evaluation": 455,
      "category": "Blunder",
      "fen": "4k2r/4n1pp/2b2p2/b2p4/8/2P2P2/1P4PP/R1B1K2R w KQk - 0 22",
      "san": "Bxa5",
      "best": "b4c5",
      "best_san": "Bc5",
      "is_capture": true
    },
    {
      "move_number": 22,
      "move": "a1a5",
      "mover": "white",
      "to_move": "black",
      "mate_in": null,
      "evaluation": 442,
      "category": "Best",
      "fen": "4k2r/4n1pp/2b2p2/R2p4/8/2P2P2/1P4PP/2B1K2R b Kk - 0 22",
      "san": "Rxa5",
      "best": "a1a5",
      "best_san": "Rxa5",
      "is_capture": true
    },
    {
      "move_number": 22,
      "move": "e8g8",
      "mover": "black",
      "to_move": "white",
      "mate_in": null,
      "evaluation": 453,
      "category": "Best",
      "fen": "5rk1/4n1pp/2b2p2/R2p4/8/2P2P2/1P4PP/2B1K2R w K - 1 23",
      "san": "O-O",
      "best": "e8g8",
      "best_san": "O-O",
      "is_capture": false
    },
    {
      "move_number": 23,
      "move": "a5a7",
      "mover": "white",
      "to_move": "black",
      "mate_in": null,
      "evaluation": 422,
      "category": "Excellent",
      "fen": "5rk1/R3n1pp/2b2p2/3p4/8/2P2P2/1P4PP/2B1K2R b K - 2 23",
      "san": "Ra7",
      "best": "e1g1",
      "best_san": "O-O",
      "is_capture": false
    },
    {
      "move_number": 23,
      "move": "f8e8",
      "mover": "black",
      "to_move": "white",
      "mate_in": null,
      "evaluation": 453,
      "category": "Excellent",
      "fen": "4r1k1/R3n1pp/2b2p2/3p4/8/2P2P2/1P4PP/2B1K2R w K - 3 24",
      "san": "Re8",
      "best": "e7g6",
      "best_san": "Ng6",
      "is_capture": false
    },
    {
      "move_number": 24,
      "move": "c1f4",
      "mover": "white",
      "to_move": "black",
      "mate_in": null,
      "evaluation": -325,
      "category": "Blunder",
      "fen": "4r1k1/R3n1pp/2b2p2/3p4/5B2/2P2P2/1P4PP/4K2R b K - 4 24",
      "san": "Bf4",
      "best": "e1f2",
      "best_san": "Kf2",
      "is_capture": false
    },
    {
      "move_number": 24,
      "move": "e7g6",
      "mover": "black",
      "to_move": "white",
      "mate_in": null,
      "evaluation": 23,
      "category": "Miss",
      "fen": "4r1k1/R5pp/2b2pn1/3p4/5B2/2P2P2/1P4PP/4K2R w K - 5 25",
      "san": "Ng6+",
      "best": "e7c8",
      "best_san": "Nc8+",
      "is_capture": false
    },
    {
      "move_number": 25,
      "move": "e1f2",
      "mover": "white",
      "to_move": "black",
      "mate_in": null,
      "evaluation": -10,
      "category": "Good",
      "fen": "4r1k1/R5pp/2b2pn1/3p4/5B2/2P2P2/1P3KPP/7R b - - 6 25",
      "san": "Kf2",
      "best": "f4e3",
      "best_san": "Be3",
      "is_capture": false
    },
    {
      "move_number": 25,
      "move": "g6f4",
      "mover": "black",
      "to_move": "white",
      "mate_in": null,
      "evaluation": -7,
      "category": "Best",
      "fen": "4r1k1/R5pp/2b2p2/3p4/5n2/2P2P2/1P3KPP/7R w - - 0 26",
      "san": "Nxf4",
      "best": "g6f4",
      "best_san": "Nxf4",
      "is_capture": true
    },
    {
      "move_number": 26,
      "move": "f2g3",
      "mover": "white",
      "to_move": "black",
      "mate_in": null,
      "evaluation": -7,
      "category": "Best",
      "fen": "4r1k1/R5pp/2b2p2/3p4/5n2/2P2PK1/1P4PP/7R b - - 1 26",
      "san": "Kg3",
      "best": "f2g3",
      "best_san": "Kg3",
      "is_capture": false
    },
    {
      "move_number": 26,
      "move": "f4e6",
      "mover": "black",
      "to_move": "white",
      "mate_in": null,
      "evaluation": 10,
      "category": "Excellent",
      "fen": "4r1k1/R5pp/2b1np2/3p4/8/2P2PK1/1P4PP/7R w - - 2 27",
      "san": "Ne6",
      "best": "g7g5",
      "best_san": "g5",
      "is_capture": false
    },
    {
      "move_number": 27,
      "move": "h1e1",
      "mover": "white",
      "to_move": "black",
      "mate_in": null,
      "evaluation": 0,
      "category": "Excellent",
      "fen": "4r1k1/R5pp/2b1np2/3p4/8/2P2PK1/1P4PP/4R3 b - - 3 27",
      "san": "Re1",
      "best": "h1a1",
      "best_san": "Rha1",
      "is_capture": false
    },
    {
      "move_number": 27,
      "move": "e6c5",
      "mover": "black",
      "to_move": "white",
      "mate_in": null,
      "evaluation": 50,
      "category": "Good",
      "fen": "4r1k1/R5pp/2b2p2/2np4/8/2P2PK1/1P4PP/4R3 w - - 4 28",
      "san": "Nc5",
      "best": "g8f8",
      "best_san": "Kf8",
      "is_capture": false
    },
    {
      "move_number": 28,
      "move": "e1e8",
      "mover": "white",
      "to_move": "black",
      "mate_in": null,
      "evaluation": 51,
      "category": "Excellent",
      "fen": "4R1k1/R5pp/2b2p2/2np4/8/2P2PK1/1P4PP/8 b - - 0 28",
      "san": "Rxe8+",
      "best": "e1e8",
      "best_san": "Rxe8+",
      "is_capture": true
    },
    {
      "move_number": 28,
      "move": "c6e8",
      "mover": "black",
      "to_move": "white",
      "mate_in": null,
      "evaluation": 56,
      "category": "Forced",
      "fen": "4b1k1/R5pp/5p2/2np4/8/2P2PK1/1P4PP/8 w - - 0 29",
      "san": "Bxe8",
      "best": "c6e8",
      "best_san": "Bxe8",
      "is_capture": true
    },
    {
      "move_number": 29,
      "move": "a7a8",
      "mover": "white",
      "to_move": "black",
      "mate_in": null,
      "evaluation": 29,
      "category": "Good",
      "fen": "R3b1k1/6pp/5p2/2np4/8/2P2PK1/1P4PP/8 b - - 1 29",
      "san": "Ra8",
      "best": "a7c7",
      "best_san": "Rc7",
      "is_capture": false
    },
    {
      "move_number": 29,
      "move": "g8f8",
      "mover": "black",
      "to_move": "white",
      "mate_in": null,
      "evaluation": 41,
      "category": "Best",
      "fen": "R3bk2/6pp/5p2/2np4/8/2P2PK1/1P4PP/8 w - - 2 30",
      "san": "Kf8",
      "best": "g8f8",
      "best_san": "Kf8",
      "is_capture": false
    },
    {
      "move_number": 30,
      "move": "b2b4",
      "mover": "white",
      "to_move": "black",
      "mate_in": null,
      "evaluation": 44,
      "category": "Best",
      "fen": "R3bk2/6pp/5p2/2np4/1P6/2P2PK1/6PP/8 b - - 0 30",
      "san": "b4",
      "best": "b2b4",
      "best_san": "b4",
      "is_capture": false
    },
    {
      "move_number": 30,
      "move": "c5b3",
      "mover": "black",
      "to_move": "white",
      "mate_in": null,
      "evaluation": 346,
      "category": "Blunder",
      "fen": "R3bk2/6pp/5p2/3p4/1P6/1nP2PK1/6PP/8 w - - 1 31",
      "san": "Nb3",
      "best": "c5a4",
      "best_san": "Na4",
      "is_capture": false
    },
    {
      "move_number": 31,
      "move": "b4b5",
      "mover": "white",
      "to_move": "black",
      "mate_in": null,
      "evaluation": 428,
      "category": "Best",
      "fen": "R3bk2/6pp/5p2/1P1p4/8/1nP2PK1/6PP/8 b - - 0 31",
      "san": "b5",
      "best": "b4b5",
      "best_san": "b5",
      "is_capture": false
    },
    {
      "move_number": 31,
      "move": "b3d2",
      "mover": "black",
      "to_move": "white",
      "mate_in": null,
      "evaluation": 660,
      "category": "Inaccuracy",
      "fen": "R3bk2/6pp/5p2/1P1p4/8/2P2PK1/3n2PP/8 w - - 1 32",
      "san": "Nd2",
      "best": "f8e7",
      "best_san": "Ke7",
      "is_capture": false
    },
    {
      "move_number": 32,
      "move": "b5b6",
      "mover": "white",
      "to_move": "black",
      "mate_in": null,
      "evaluation": 678,
      "category": "Best",
      "fen": "R3bk2/6pp/1P3p2/3p4/8/2P2PK1/3n2PP/8 b - - 0 32",
      "san": "b6",
      "best": "b5b6",
      "best_san": "b6",
      "is_capture": false
    },
    {
      "move_number": 32,
      "move": "d5d4",
      "mover": "black",
      "to_move": "white",
      "mate_in": null,
      "evaluation": 818,
      "category": "Good",
      "fen": "R3bk2/6pp/1P3p2/8/3p4/2P2PK1/3n2PP/8 w - - 0 33",
      "san": "d4",
      "best": "f8e7",
      "best_san": "Ke7",
      "is_capture": false
    },
    {
      "move_number": 33,
      "move": "b6b7",
      "mover": "white",
      "to_move": "black",
      "mate_in": null,
      "evaluation": 890,
      "category": "Best",
      "fen": "R3bk2/1P4pp/5p2/8/3p4/2P2PK1/3n2PP/8 b - - 0 33",
      "san": "b7",
      "best": "b6b7",
      "best_san": "b7",
      "is_capture": false
    },
    {
      "move_number": 33,
      "move": "d4c3",
      "mover": "black",
      "to_move": "white",
      "mate_in": 9,
      "evaluation": 9991,
      "category": "Best",
      "fen": "R3bk2/1P4pp/5p2/8/8/2p2PK1/3n2PP/8 w - - 0 34",
      "san": "dxc3",
      "best": "d2f1",
      "best_san": "Nf1+",
      "is_capture": true
    },
    {
      "move_number": 34,
      "move": "b7b8q",
      "mover": "white",
      "to_move": "black",
      "mate_in": 8,
      "evaluation": 9992,
      "category": "Best",
      "fen": "RQ2bk2/6pp/5p2/8/8/2p2PK1/3n2PP/8 b - - 0 34",
      "san": "b8=Q",
      "best": "b7b8q",
      "best_san": "b8=Q",
      "is_capture": false
    },
    {
      "move_number": 34,
      "move": "f8f7",
      "mover": "black",
      "to_move": "white",
      "mate_in": 1,
      "evaluation": 9999,
      "category": "Excellent",
      "fen": "RQ2b3/5kpp/5p2/8/8/2p2PK1/3n2PP/8 w - - 1 35",
      "san": "Kf7",
      "best": "f8e7",
      "best_san": "Ke7",
      "is_capture": false
    },
    {
      "move_number": 35,
      "move": "b8e8",
      "mover": "white",
      "to_move": "black",
      "mate_in": 0,
      "evaluation": 10000,
      "category": "Best",
      "fen": "R3Q3/5kpp/5p2/8/8/2p2PK1/3n2PP/8 b - - 0 35",
      "san": "Qxe8#",
      "best": "b8e8",
      "best_san": "Qxe8#",
      "is_capture": true
    }
  ],
  "eval_history": [
    37,
    47,
    35,
    33,
    25,
    33,
    -50,
    -43,
    -40,
    -43,
    -437,
    -424,
    -417,
    -25,
    -25,
    154,
    -43,
    79,
    -3,
    2,
    -34,
    -19,
    -105,
    27,
    12,
    11,
    -8,
    41,
    -99,
    -96,
    -352,
    -252,
    -261,
    -168,
    -173,
    -78,
    -97,
    -27,
    -124,
    -22,
    -22,
    455,
    442,
    453,
    422,
    453,
    -325,
    23,
    -10,
    -7,
    -7,
    10,
    0,
    50,
    51,
    56,
    29,
    41,
    44,
    346,
    428,
    660,
    678,
    818,
    890,
    9991,
    9992,
    9999,
    10000
  ]
};
